name: Keioboys
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --bstarsmatchuild-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 3.3.0
  cloud_functions: 3.3.8
  firebase_storage: ^10.3.2
  firebase_core: 1.19.2
  firebase_analytics: ^9.3.1
  firebase_auth: ^3.6.4
  firebase_messaging: ^12.0.2
  firebase_crashlytics: ^2.8.7
  flutter_bloc: ^7.3.3
  font_awesome_flutter: 8.8.1
  geolocator: ^7.6.2
  another_flushbar: ^1.10.29
  intl: 0.17.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  material_design_icons_flutter: 4.0.5345
  file_picker: ^4.0.1
  page_indicator: 0.3.0
  fluttery_dart2: 0.0.9
  extended_image: 6.2.1
  package_info: ^0.4.3
  image_cropper: 1.4.1
#  webview_flutter: 0.3.24
  selectable_autolink_text: 2.3.0
  equatable: 1.2.5
  location: ^4.4.0
  universal_platform: ^1.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: 0.1.3
  shared_preferences: 2.0.6
  url_launcher: ^6.1.5
  http: ^0.13.3
  in_app_review: ^2.0.4
  platform: ^3.1.0
#  image_picker_web: ^2.0.3+1
#  image_cropping: ^0.0.5

  crop: 0.4.1
  image: ^3.0.2
  image_picker: ^0.8.4
  image_picker_for_web: ^2.1.3
  universal_html: ^2.0.8
  youtube_player_iframe: ^2.3.0
  video_player: ^2.2.5
  google_geocoding: ^0.2.0
  seo_renderer: ^0.6.0
#  easy_web_view: any
  webviewx: ^0.2.1
  responsive_framework: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: 0.9.0
  universal_html: ^2.0.8
  js: ^0.6.3
  dio: ^4.0.1

flutter_icons:
  image_path: "assets/images/appIcon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/appIcon.png
    - assets/images/explanation1.jpg
    - assets/images/explanation2.jpg
    - assets/images/explanation3.jpg
    - assets/images/pp.PNG
    - assets/images/ts.PNG
    - assets/images/beginner.png


  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/Avenir-Next-LT-Pro-Ultra-Light-Condensed.ttf
#        - asset: assets/fonts/DancingScript-SemiBold.ttf

    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf